name: Python application

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        # Add commands to run your tests here
    - name: Deploy to PythonAnywhere
      run: |
        curl -H "Authorization: Token ${TOKEN}" \
             -X POST \
             -d "github_url=https://github.com/pavankumar19992208/face_recog&branch=main" \
             https://www.pythonanywhere.com/api/v0/user/pavantech988/github_sync/
      env:
        TOKEN: ${{ secrets.PA_TOKEN }}